/**
 * Action-Level Metadata for AI Cost-Aware Decision Making
 *
 * Provides detailed metadata for all actions across all tools (see ACTION_COUNT in action-counts.ts).
 * This enables AI to make informed decisions about:
 * - API quota costs
 * - Read-only vs destructive operations
 * - Operations requiring confirmation
 * - Typical latency expectations
 * - Quota savings opportunities
 */

import { TOOL_ACTIONS } from '../mcp/completions.js';

export interface ActionMetadata {
  /** Is this a read-only operation? */
  readOnly: boolean;
  /** Number of Google Sheets API calls (or 'dynamic' if varies) */
  apiCalls: number | 'dynamic';
  /** Quota cost (1 = one API call, or formula for dynamic) */
  quotaCost: number | string;
  /** Does this operation require user confirmation? */
  requiresConfirmation: boolean;
  /** Is this a destructive operation (deletes/modifies data)? */
  destructive: boolean;
  /** Is this operation idempotent (safe to retry)? */
  idempotent: boolean;
  /** Typical latency range */
  typicalLatency?: string;
  /** Quota savings description (for batch operations) */
  savings?: string;
}

/**
 * Complete action metadata for all actions (count derived from ACTION_COUNT)
 */
const RAW_ACTION_METADATA: Record<string, Record<string, ActionMetadata>> = {
  sheets_advanced: {
    add_named_range: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: false,
      typicalLatency: '300-800ms',
    },
    update_named_range: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    delete_named_range: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    list_named_ranges: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
    get_named_range: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
    add_protected_range: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: false,
      typicalLatency: '300-800ms',
    },
    update_protected_range: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    delete_protected_range: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    list_protected_ranges: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
    set_metadata: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    get_metadata: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
    delete_metadata: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    add_banding: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: false,
      typicalLatency: '300-800ms',
    },
    update_banding: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    delete_banding: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    list_banding: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
    create_table: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: false,
      typicalLatency: '300-800ms',
    },
    delete_table: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    list_tables: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
  },
  sheets_analyze: {
    comprehensive: {
      readOnly: true,
      apiCalls: 'dynamic',
      quotaCost: 'dynamic',
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '3-15s',
    },
    analyze_data: {
      readOnly: true,
      apiCalls: 'dynamic',
      quotaCost: 'dynamic',
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '3-15s',
    },
    suggest_visualization: {
      readOnly: true,
      apiCalls: 'dynamic',
      quotaCost: 'dynamic',
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '3-15s',
    },
    generate_formula: {
      readOnly: true,
      apiCalls: 'dynamic',
      quotaCost: 'dynamic',
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '3-15s',
    },
    detect_patterns: {
      readOnly: true,
      apiCalls: 'dynamic',
      quotaCost: 'dynamic',
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '3-15s',
    },
    analyze_structure: {
      readOnly: true,
      apiCalls: 'dynamic',
      quotaCost: 'dynamic',
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '3-15s',
    },
    analyze_quality: {
      readOnly: true,
      apiCalls: 'dynamic',
      quotaCost: 'dynamic',
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '3-15s',
    },
    analyze_performance: {
      readOnly: true,
      apiCalls: 'dynamic',
      quotaCost: 'dynamic',
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '3-15s',
    },
    analyze_formulas: {
      readOnly: true,
      apiCalls: 'dynamic',
      quotaCost: 'dynamic',
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '3-15s',
    },
    query_natural_language: {
      readOnly: true,
      apiCalls: 'dynamic',
      quotaCost: 'dynamic',
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '3-15s',
    },
    explain_analysis: {
      readOnly: true,
      apiCalls: 'dynamic',
      quotaCost: 'dynamic',
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '3-15s',
    },
    scout: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
    plan: {
      readOnly: true,
      apiCalls: 'dynamic',
      quotaCost: 'dynamic',
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '1-3s',
    },
    execute_plan: {
      readOnly: true,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '50-200ms',
    },
    drill_down: {
      readOnly: true,
      apiCalls: 'dynamic',
      quotaCost: 'dynamic',
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-800ms',
    },
    generate_actions: {
      readOnly: true,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-800ms',
    },
  },
  sheets_auth: {
    status: {
      readOnly: true,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '<50ms',
    },
    login: {
      readOnly: false,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: false,
      typicalLatency: '<50ms',
    },
    callback: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: false,
      typicalLatency: '300-800ms',
    },
    logout: {
      readOnly: false,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '<50ms',
    },
  },
  sheets_collaborate: {
    share_add: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    share_update: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    share_remove: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: true,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    share_list: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    share_get: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    share_transfer_ownership: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: true,
      destructive: true,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    share_set_link: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    share_get_link: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    comment_add: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    comment_update: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    comment_delete: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: true,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    comment_list: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    comment_get: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    comment_resolve: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    comment_reopen: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    comment_add_reply: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    comment_update_reply: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    comment_delete_reply: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: true,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    version_list_revisions: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    version_get_revision: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    version_restore_revision: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: true,
      destructive: true,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    version_keep_revision: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    version_create_snapshot: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    version_list_snapshots: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    version_restore_snapshot: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: true,
      destructive: true,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    version_delete_snapshot: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: true,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    version_compare: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
    version_export: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
  },
  sheets_composite: {
    import_csv: {
      readOnly: false,
      apiCalls: 'dynamic',
      quotaCost: 'dynamic',
      requiresConfirmation: false,
      destructive: true,
      idempotent: false,
      typicalLatency: '500-5000ms',
    },
    smart_append: {
      readOnly: false,
      apiCalls: 'dynamic',
      quotaCost: 'dynamic',
      requiresConfirmation: false,
      destructive: true,
      idempotent: false,
      typicalLatency: '500-5000ms',
    },
    bulk_update: {
      readOnly: false,
      apiCalls: 'dynamic',
      quotaCost: 'dynamic',
      requiresConfirmation: false,
      destructive: true,
      idempotent: false,
      typicalLatency: '500-5000ms',
    },
    deduplicate: {
      readOnly: false,
      apiCalls: 'dynamic',
      quotaCost: 'dynamic',
      requiresConfirmation: false,
      destructive: true,
      idempotent: false,
      typicalLatency: '500-5000ms',
    },
  },
  sheets_confirm: {
    request: {
      readOnly: false,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: false,
      typicalLatency: '<50ms',
    },
    get_stats: {
      readOnly: true,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '<50ms',
    },
  },
  sheets_core: {
    get: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
    create: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: false,
      typicalLatency: '300-800ms',
    },
    copy: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: false,
      typicalLatency: '300-800ms',
    },
    update_properties: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    get_url: {
      readOnly: true,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '<50ms',
    },
    batch_get: {
      readOnly: true,
      apiCalls: 'dynamic',
      quotaCost: 'dynamic',
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '500-3000ms',
    },
    get_comprehensive: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
    list: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
    add_sheet: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: false,
      typicalLatency: '300-800ms',
    },
    delete_sheet: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: true,
      destructive: true,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    duplicate_sheet: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: false,
      typicalLatency: '300-800ms',
    },
    update_sheet: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    copy_sheet_to: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: false,
      typicalLatency: '300-800ms',
    },
    list_sheets: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
    get_sheet: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
  },
  sheets_data: {
    read: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
    write: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: true,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    append: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: false,
      typicalLatency: '300-800ms',
    },
    clear: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: true,
      destructive: true,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    batch_read: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
    batch_write: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: true,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    batch_clear: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: true,
      destructive: true,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    find_replace: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: true,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    add_note: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: false,
      typicalLatency: '300-800ms',
    },
    get_note: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
    clear_note: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: true,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    set_hyperlink: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    clear_hyperlink: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: true,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    merge_cells: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: true,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    unmerge_cells: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: true,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    get_merges: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
    cut_paste: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: true,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    copy_paste: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: true,
      idempotent: false,
      typicalLatency: '300-800ms',
    },
  },
  sheets_dimensions: {
    insert_rows: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    insert_columns: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    delete_rows: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: true,
      destructive: true,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    delete_columns: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: true,
      destructive: true,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    move_rows: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    move_columns: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    resize_rows: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    resize_columns: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    auto_resize: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    hide_rows: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    hide_columns: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    show_rows: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    show_columns: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    freeze_rows: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    freeze_columns: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    group_rows: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    group_columns: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    ungroup_rows: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    ungroup_columns: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    append_rows: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: false,
      typicalLatency: '300-800ms',
    },
    append_columns: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: false,
      typicalLatency: '300-800ms',
    },
    set_basic_filter: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    clear_basic_filter: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: true,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    get_basic_filter: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
    filter_update_filter_criteria: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    sort_range: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    trim_whitespace: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: true,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    randomize_range: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: true,
      idempotent: false, // Randomize produces different results each call
      typicalLatency: '300-800ms',
    },
    text_to_columns: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: true,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    auto_fill: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: true,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    create_filter_view: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: false,
      typicalLatency: '300-800ms',
    },
    duplicate_filter_view: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: false,
      typicalLatency: '300-800ms',
    },
    update_filter_view: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    delete_filter_view: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: true,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    list_filter_views: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
    get_filter_view: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
    create_slicer: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: false,
      typicalLatency: '300-800ms',
    },
    update_slicer: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    delete_slicer: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: true,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    list_slicers: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
  },
  sheets_fix: {
    fix: {
      readOnly: false,
      apiCalls: 'dynamic',
      quotaCost: 'dynamic',
      requiresConfirmation: false,
      destructive: true,
      idempotent: true,
      typicalLatency: '1-10s',
    },
  },
  sheets_format: {
    set_format: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    suggest_format: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
    set_background: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    set_text_format: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    set_number_format: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    set_alignment: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    set_borders: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    clear_format: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    apply_preset: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    auto_fit: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    rule_add_conditional_format: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    rule_update_conditional_format: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    rule_delete_conditional_format: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    rule_list_conditional_formats: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    set_data_validation: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    clear_data_validation: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    list_data_validations: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
    add_conditional_format_rule: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: false,
      typicalLatency: '300-800ms',
    },
  },
  sheets_history: {
    list: {
      readOnly: true,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '<50ms',
    },
    get: {
      readOnly: true,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '<50ms',
    },
    stats: {
      readOnly: true,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '<50ms',
    },
    undo: {
      readOnly: false,
      apiCalls: 'dynamic',
      quotaCost: 'dynamic',
      requiresConfirmation: false,
      destructive: true,
      idempotent: false,
      typicalLatency: '500-3000ms',
    },
    redo: {
      readOnly: false,
      apiCalls: 'dynamic',
      quotaCost: 'dynamic',
      requiresConfirmation: false,
      destructive: true,
      idempotent: false,
      typicalLatency: '500-3000ms',
    },
    revert_to: {
      readOnly: false,
      apiCalls: 'dynamic',
      quotaCost: 'dynamic',
      requiresConfirmation: true,
      destructive: true,
      idempotent: false,
      typicalLatency: '500-3000ms',
    },
    clear: {
      readOnly: false,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: true,
      destructive: true,
      idempotent: true,
      typicalLatency: '<50ms',
    },
  },
  sheets_quality: {
    validate: {
      readOnly: true,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '<50ms',
    },
    detect_conflicts: {
      readOnly: true,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '<50ms',
    },
    resolve_conflict: {
      readOnly: false,
      apiCalls: 'dynamic',
      quotaCost: 'dynamic',
      requiresConfirmation: false,
      destructive: true,
      idempotent: true,
      typicalLatency: '500-3000ms',
    },
    analyze_impact: {
      readOnly: true,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '<50ms',
    },
  },
  sheets_session: {
    set_active: {
      readOnly: false,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '<50ms',
    },
    get_active: {
      readOnly: true,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '<50ms',
    },
    get_context: {
      readOnly: true,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '<50ms',
    },
    record_operation: {
      readOnly: false,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: false,
      typicalLatency: '<50ms',
    },
    get_last_operation: {
      readOnly: true,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '<50ms',
    },
    get_history: {
      readOnly: true,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '<50ms',
    },
    find_by_reference: {
      readOnly: false,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '<50ms',
    },
    update_preferences: {
      readOnly: false,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '<50ms',
    },
    get_preferences: {
      readOnly: true,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '<50ms',
    },
    set_pending: {
      readOnly: false,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '<50ms',
    },
    get_pending: {
      readOnly: true,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '<50ms',
    },
    clear_pending: {
      readOnly: false,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '<50ms',
    },
    reset: {
      readOnly: false,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '<50ms',
    },
  },
  sheets_transaction: {
    begin: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: false,
      typicalLatency: '300-800ms',
    },
    queue: {
      readOnly: false,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: false,
      typicalLatency: '<50ms',
    },
    commit: {
      readOnly: false,
      apiCalls: 'dynamic',
      quotaCost: 'dynamic',
      requiresConfirmation: false,
      destructive: true,
      idempotent: false,
      typicalLatency: '500-3000ms',
      savings: 'Batch operations: N actions -> 1 API call',
    },
    rollback: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: false,
      typicalLatency: '300-800ms',
    },
    status: {
      readOnly: true,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '<50ms',
    },
    list: {
      readOnly: true,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '<50ms',
    },
  },
  sheets_visualize: {
    chart_create: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    suggest_chart: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
    chart_update: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    chart_delete: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    chart_list: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    chart_get: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    chart_move: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    chart_resize: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    chart_update_data_range: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    pivot_create: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    suggest_pivot: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
    pivot_update: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    pivot_delete: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    pivot_list: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    pivot_get: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    pivot_refresh: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
  },

  // ============================================
  // TIER 7: ENTERPRISE HANDLERS
  // ============================================

  sheets_templates: {
    list: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
    get: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
    create: {
      readOnly: false,
      apiCalls: 2,
      quotaCost: 2,
      requiresConfirmation: false,
      destructive: false,
      idempotent: false,
      typicalLatency: '500-1500ms',
    },
    apply: {
      readOnly: false,
      apiCalls: 'dynamic',
      quotaCost: '2-10 depending on template complexity',
      requiresConfirmation: true,
      destructive: true,
      idempotent: false,
      typicalLatency: '1000-5000ms',
    },
    update: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    delete: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: true,
      destructive: true,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    preview: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
    import_builtin: {
      readOnly: false,
      apiCalls: 2,
      quotaCost: 2,
      requiresConfirmation: false,
      destructive: false,
      idempotent: false,
      typicalLatency: '500-1500ms',
    },
  },

  sheets_bigquery: {
    connect: {
      readOnly: false,
      apiCalls: 2,
      quotaCost: 2,
      requiresConfirmation: false,
      destructive: false,
      idempotent: false,
      typicalLatency: '1000-3000ms',
    },
    connect_looker: {
      readOnly: false,
      apiCalls: 2,
      quotaCost: 2,
      requiresConfirmation: false,
      destructive: false,
      idempotent: false,
      typicalLatency: '1000-3000ms',
    },
    disconnect: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: true,
      destructive: true,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    list_connections: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
    get_connection: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
    query: {
      readOnly: true,
      apiCalls: 2,
      quotaCost: 'BigQuery pricing applies',
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '2000-30000ms',
    },
    preview: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 'BigQuery dry-run (free)',
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '500-2000ms',
    },
    refresh: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 'BigQuery pricing applies',
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '2000-60000ms',
    },
    cancel_refresh: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
    list_datasets: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '500-2000ms',
    },
    list_tables: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '500-2000ms',
    },
    get_table_schema: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '500-2000ms',
    },
    export_to_bigquery: {
      readOnly: false,
      apiCalls: 2,
      quotaCost: 'BigQuery pricing applies',
      requiresConfirmation: true,
      destructive: true,
      idempotent: false,
      typicalLatency: '5000-120000ms',
    },
    import_from_bigquery: {
      readOnly: false,
      apiCalls: 3,
      quotaCost: 'BigQuery pricing applies',
      requiresConfirmation: true,
      destructive: false,
      idempotent: false,
      typicalLatency: '5000-120000ms',
    },
  },

  sheets_appsscript: {
    create: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: false,
      typicalLatency: '1000-3000ms',
    },
    get: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '500-2000ms',
    },
    get_content: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '500-2000ms',
    },
    update_content: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: true,
      destructive: true,
      idempotent: true,
      typicalLatency: '500-2000ms',
    },
    create_version: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: false,
      typicalLatency: '1000-3000ms',
    },
    list_versions: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '500-2000ms',
    },
    get_version: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '500-2000ms',
    },
    deploy: {
      readOnly: false,
      apiCalls: 2,
      quotaCost: 2,
      requiresConfirmation: true,
      destructive: false,
      idempotent: false,
      typicalLatency: '2000-10000ms',
    },
    list_deployments: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '500-2000ms',
    },
    get_deployment: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '500-2000ms',
    },
    undeploy: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: true,
      destructive: true,
      idempotent: true,
      typicalLatency: '500-2000ms',
    },
    run: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 'Apps Script quota applies',
      requiresConfirmation: true,
      destructive: true,
      idempotent: false,
      typicalLatency: '1000-30000ms',
    },
    list_processes: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '500-2000ms',
    },
    get_metrics: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '500-2000ms',
    },
  },

  sheets_webhook: {
    register: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: false,
      typicalLatency: '300-800ms',
    },
    unregister: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: true,
      idempotent: true,
      typicalLatency: '300-800ms',
    },
    list: {
      readOnly: true,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '50-100ms',
    },
    get: {
      readOnly: true,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '50-100ms',
    },
    test: {
      readOnly: true,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '100-500ms',
    },
    get_stats: {
      readOnly: true,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '50-100ms',
    },
  },

  sheets_dependencies: {
    build: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '500-5000ms',
    },
    analyze_impact: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '500-3000ms',
    },
    detect_cycles: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '500-3000ms',
    },
    get_dependencies: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-1000ms',
    },
    get_dependents: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-1000ms',
    },
    get_stats: {
      readOnly: true,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '50-100ms',
    },
    export_dot: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '500-3000ms',
    },
  },

  sheets_compute: {
    evaluate: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
    aggregate: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
    statistical: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-800ms',
    },
    regression: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-1000ms',
    },
    forecast: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-1000ms',
    },
    matrix_op: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-800ms',
    },
    pivot_compute: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '300-1000ms',
    },
    custom_function: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
    batch_compute: {
      readOnly: true,
      apiCalls: 'dynamic',
      quotaCost: 'dynamic',
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '500-3000ms',
    },
    explain_formula: {
      readOnly: true,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '50-200ms',
    },
  },

  sheets_agent: {
    plan: {
      readOnly: true,
      apiCalls: 'dynamic',
      quotaCost: 'dynamic',
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '1-5s',
    },
    execute: {
      readOnly: false,
      apiCalls: 'dynamic',
      quotaCost: 'dynamic',
      requiresConfirmation: true,
      destructive: true,
      idempotent: false,
      typicalLatency: '5-60s',
    },
    execute_step: {
      readOnly: false,
      apiCalls: 'dynamic',
      quotaCost: 'dynamic',
      requiresConfirmation: false,
      destructive: true,
      idempotent: false,
      typicalLatency: '1-10s',
    },
    observe: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-500ms',
    },
    rollback: {
      readOnly: false,
      apiCalls: 'dynamic',
      quotaCost: 'dynamic',
      requiresConfirmation: true,
      destructive: true,
      idempotent: false,
      typicalLatency: '500-5000ms',
    },
    get_status: {
      readOnly: true,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '<50ms',
    },
    list_plans: {
      readOnly: true,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '<50ms',
    },
    resume: {
      readOnly: false,
      apiCalls: 'dynamic',
      quotaCost: 'dynamic',
      requiresConfirmation: false,
      destructive: true,
      idempotent: false,
      typicalLatency: '1-30s',
    },
  },

  sheets_federation: {
    call_remote: {
      readOnly: false,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: true,
      destructive: false,
      idempotent: false,
      typicalLatency: '500-5000ms',
    },
    list_servers: {
      readOnly: true,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '50-150ms',
    },
    get_server_tools: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-2000ms',
    },
    validate_connection: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '100-2000ms',
    },
  },

  sheets_connectors: {
    list_connectors: {
      readOnly: true,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '<50ms',
    },
    configure: {
      readOnly: false,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '<100ms',
    },
    query: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: false,
      typicalLatency: '500-5000ms',
      savings: 'Caches responses per connector TTL',
    },
    batch_query: {
      readOnly: true,
      apiCalls: 'dynamic',
      quotaCost: 'dynamic',
      requiresConfirmation: false,
      destructive: false,
      idempotent: false,
      typicalLatency: '1-10s',
      savings: 'Parallel connector queries',
    },
    subscribe: {
      readOnly: false,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '<100ms',
    },
    unsubscribe: {
      readOnly: false,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '<100ms',
    },
    list_subscriptions: {
      readOnly: true,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '<50ms',
    },
    transform: {
      readOnly: true,
      apiCalls: 0,
      quotaCost: 0,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '50-200ms',
    },
    status: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '200-2000ms',
    },
    discover: {
      readOnly: true,
      apiCalls: 1,
      quotaCost: 1,
      requiresConfirmation: false,
      destructive: false,
      idempotent: true,
      typicalLatency: '500-3000ms',
    },
  },
};

function isReadOnlyAction(actionName: string): boolean {
  return (
    actionName.startsWith('get') ||
    actionName.startsWith('list') ||
    actionName.startsWith('read') ||
    actionName.startsWith('status') ||
    actionName.startsWith('preview') ||
    actionName.startsWith('analyze') ||
    actionName.startsWith('detect') ||
    actionName.startsWith('discover') ||
    actionName.startsWith('scout') ||
    actionName.startsWith('explain') ||
    actionName.startsWith('compare') ||
    actionName.startsWith('query_natural_language')
  );
}

function isDestructiveAction(actionName: string): boolean {
  return (
    actionName.startsWith('delete') ||
    actionName.startsWith('remove') ||
    actionName.startsWith('clear') ||
    actionName.startsWith('rollback') ||
    actionName.startsWith('revert') ||
    actionName.startsWith('restore') ||
    actionName.startsWith('undeploy') ||
    actionName.startsWith('migrate')
  );
}

function isDynamicAction(toolName: string, actionName: string): boolean {
  return (
    actionName.startsWith('batch_') ||
    actionName === 'comprehensive' ||
    actionName === 'audit_sheet' ||
    actionName === 'publish_report' ||
    actionName === 'data_pipeline' ||
    actionName === 'generate_sheet' ||
    actionName === 'generate_template' ||
    actionName.startsWith('execute') ||
    actionName === 'rollback' ||
    actionName === 'resume' ||
    toolName === 'sheets_composite'
  );
}

function inferApiCalls(toolName: string, actionName: string): number | 'dynamic' {
  if (toolName === 'sheets_session' || toolName === 'sheets_confirm') {
    return 0;
  }

  if (
    toolName === 'sheets_connectors' &&
    [
      'list_connectors',
      'configure',
      'subscribe',
      'unsubscribe',
      'list_subscriptions',
      'transform',
    ].includes(actionName)
  ) {
    return 0;
  }

  if (isDynamicAction(toolName, actionName)) {
    return 'dynamic';
  }

  return 1;
}

function inferIdempotent(actionName: string, readOnly: boolean, destructive: boolean): boolean {
  if (readOnly) {
    return true;
  }

  if (actionName.startsWith('create') || actionName.startsWith('add') || actionName === 'append') {
    return false;
  }

  if (actionName.startsWith('run') || actionName.startsWith('execute')) {
    return false;
  }

  if (destructive) {
    return true;
  }

  if (actionName.startsWith('update') || actionName.startsWith('set')) {
    return true;
  }

  return false;
}

function inferTypicalLatency(
  apiCalls: number | 'dynamic',
  readOnly: boolean,
  toolName: string
): string {
  if (apiCalls === 0) {
    return '<100ms';
  }

  if (apiCalls === 'dynamic') {
    return toolName === 'sheets_analyze' || toolName === 'sheets_agent' ? '1-30s' : '1-10s';
  }

  return readOnly ? '200-800ms' : '300-1200ms';
}

function buildDefaultActionMetadata(toolName: string, actionName: string): ActionMetadata {
  const readOnly = isReadOnlyAction(actionName);
  const destructive = isDestructiveAction(actionName);
  const apiCalls = inferApiCalls(toolName, actionName);

  const metadata: ActionMetadata = {
    readOnly,
    apiCalls,
    quotaCost: apiCalls === 'dynamic' ? 'dynamic' : apiCalls,
    requiresConfirmation:
      destructive &&
      (actionName.startsWith('delete') ||
        actionName.startsWith('remove') ||
        actionName.startsWith('clear') ||
        actionName.startsWith('rollback') ||
        actionName.startsWith('revert') ||
        actionName.startsWith('restore')),
    destructive,
    idempotent: inferIdempotent(actionName, readOnly, destructive),
    typicalLatency: inferTypicalLatency(apiCalls, readOnly, toolName),
  };

  if (actionName.startsWith('batch_')) {
    metadata.savings = 'Batch operation reduces round trips by combining multiple requests';
  }

  return metadata;
}

function normalizeActionMetadata(
  raw: Record<string, Record<string, ActionMetadata>>
): Record<string, Record<string, ActionMetadata>> {
  const normalized: Record<string, Record<string, ActionMetadata>> = {};

  for (const [toolName, actions] of Object.entries(TOOL_ACTIONS)) {
    const rawToolMetadata = raw[toolName] ?? {};
    normalized[toolName] = {};

    for (const actionName of actions) {
      normalized[toolName][actionName] =
        rawToolMetadata[actionName] ?? buildDefaultActionMetadata(toolName, actionName);
    }
  }

  return normalized;
}

/**
 * Complete action metadata for all actions, normalized against TOOL_ACTIONS.
 * - Missing action entries are backfilled with deterministic defaults.
 * - Stale entries for removed/renamed actions are excluded.
 */
export const ACTION_METADATA: Record<
  string,
  Record<string, ActionMetadata>
> = normalizeActionMetadata(RAW_ACTION_METADATA);
