#!/usr/bin/env tsx
/**
 * ServalSheets Documentation Auto-Sync
 *
 * Reads audit results and automatically updates documentation:
 * - README.md: Current audit score
 * - docs/STATUS.md: Top issues
 * - CHANGELOG.md: Audit results on release
 *
 * Usage:
 *   npm run docs:sync          # Update docs
 *   npm run docs:sync --commit # Update and commit
 */

import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';

const RESULTS_FILE = 'audit-output/results.json';
const README_FILE = 'README.md';
const STATUS_FILE = 'docs/STATUS.md';

console.log('═══════════════════════════════════════════════════════════');
console.log('   Documentation Auto-Sync from Audit Results');
console.log('═══════════════════════════════════════════════════════════\n');

// Load audit results
if (!fs.existsSync(RESULTS_FILE)) {
  console.error(`❌ Error: Audit results not found: ${RESULTS_FILE}`);
  console.error('   Run: npm run audit:full');
  process.exit(1);
}

console.log('▶ Loading audit results...');
const results = JSON.parse(fs.readFileSync(RESULTS_FILE, 'utf8'));

console.log(`  Current Score: ${results.total_percentage}%`);
console.log(`  Issues: ${results.issues.length}`);
console.log('');

// Helper: Get verdict
function getVerdict(score: number): string {
  if (score >= 135) return 'Exceptional';
  if (score >= 130) return 'Excellent';
  if (score >= 120) return 'Very Good';
  if (score >= 100) return 'Good';
  if (score >= 80) return 'Fair';
  return 'Needs Work';
}

// Helper: Get badge color
function getBadgeColor(score: number): string {
  if (score >= 130) return 'brightgreen';
  if (score >= 120) return 'green';
  if (score >= 100) return 'yellowgreen';
  if (score >= 80) return 'yellow';
  return 'red';
}

let filesModified = 0;

// Update README.md
console.log('▶ Updating README.md...');
if (fs.existsSync(README_FILE)) {
  let readme = fs.readFileSync(README_FILE, 'utf8');
  const originalReadme = readme;

  // Update or add audit score badge
  const badgeColor = getBadgeColor(results.total_percentage);
  const badgeMarkdown = `![Audit Score](https://img.shields.io/badge/audit-${results.total_percentage}%25-${badgeColor})`;

  // Look for existing audit badge
  const auditBadgeRegex = /!\[Audit Score\]\(https:\/\/img\.shields\.io\/badge\/audit-[^)]+\)/;

  if (auditBadgeRegex.test(readme)) {
    readme = readme.replace(auditBadgeRegex, badgeMarkdown);
    console.log('  ✓ Updated existing audit badge');
  } else {
    // Add badge after title (first line starting with #)
    const lines = readme.split('\n');
    const titleIndex = lines.findIndex((line) => line.startsWith('# '));

    if (titleIndex !== -1) {
      // Insert badge section after title
      lines.splice(titleIndex + 1, 0, '', badgeMarkdown, '');
      readme = lines.join('\n');
      console.log('  ✓ Added audit badge');
    }
  }

  if (readme !== originalReadme) {
    fs.writeFileSync(README_FILE, readme);
    filesModified++;
  } else {
    console.log('  - No changes needed');
  }
} else {
  console.log('  ⚠️  README.md not found');
}

// Update or create docs/STATUS.md
console.log('▶ Updating docs/STATUS.md...');

const statusContent = `# ServalSheets Status

**Last Updated:** ${new Date().toISOString().split('T')[0]}

## Current Audit Score

**${results.total_percentage}%** / 140% - ${getVerdict(results.total_percentage)}

## Top Issues

${results.issues.length === 0 ? '✅ No issues identified' : ''}
${results.issues
  .slice(0, 10)
  .map(
    (issue: any, i: number) =>
      `${i + 1}. **[${issue.priority}]** ${issue.category}: ${issue.description}`
  )
  .join('\n')}

${results.issues.length > 10 ? `\n_... and ${results.issues.length - 10} more issues_\n` : ''}

## Issues by Priority

- **P0 (Critical):** ${results.issues.filter((i: any) => i.priority === 'P0').length}
- **P1 (High):** ${results.issues.filter((i: any) => i.priority === 'P1').length}
- **P2 (Medium):** ${results.issues.filter((i: any) => i.priority === 'P2').length}
- **P3 (Low):** ${results.issues.filter((i: any) => i.priority === 'P3').length}

---

_This file is automatically generated from audit results._
_Last audit: ${new Date(results.timestamp).toLocaleString()}_
`;

// Ensure docs directory exists
if (!fs.existsSync('docs')) {
  fs.mkdirSync('docs', { recursive: true });
}

// Write status file
const existingStatus = fs.existsSync(STATUS_FILE) ? fs.readFileSync(STATUS_FILE, 'utf8') : '';

if (statusContent !== existingStatus) {
  fs.writeFileSync(STATUS_FILE, statusContent);
  console.log('  ✓ Updated docs/STATUS.md');
  filesModified++;
} else {
  console.log('  - No changes needed');
}

// Summary
console.log('');
console.log('═══════════════════════════════════════════════════════════');
console.log(`   ${filesModified} file(s) modified`);
console.log('═══════════════════════════════════════════════════════════\n');

// Check if we should commit
const shouldCommit = process.argv.includes('--commit');

if (filesModified > 0) {
  if (shouldCommit) {
    console.log('▶ Committing changes...');

    try {
      execSync('git add README.md docs/STATUS.md', { stdio: 'inherit' });
      execSync(
        `git commit -m "docs: sync audit results (${results.total_percentage}%)" -m "Co-Authored-By: Claude Sonnet 4.5 <noreply@anthropic.com>"`,
        { stdio: 'inherit' }
      );
      console.log('✓ Changes committed');
    } catch (error) {
      console.error('❌ Failed to commit changes');
      process.exit(1);
    }
  } else {
    console.log('Files modified but not committed.');
    console.log('Run with --commit flag to auto-commit.');
    console.log('Or manually commit with:');
    console.log('  git add README.md docs/STATUS.md');
    console.log(`  git commit -m "docs: sync audit results (${results.total_percentage}%)"`);
  }
} else {
  console.log('No changes to commit.');
}

console.log('');
